WebPython/Apps/Wallet/urls.py
from django.urls import path

from . import views

app_name = "Wallet"

urlpatterns = [
    path('<str:wallet_name_>/', views.get_date,
         name='get_date'),
    path('', views.main_page, name='main_page'),
    path('<str:wallet_name_>/show_wallet/',
         views.show_wallet,
         name='show_wallet'),
    path('<str:wallet_name_>/<str:wallet_date_>/show_wallet/',
         views.show_wallet,
         name='show_wallet')
]

WebPython/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path(r'', include("Wallet.urls")),
    path(r'admin/', admin.site.urls),
]

WebPython/Apps/Wallet/models.py
from django.db import models


class Wallet_indentificator(models.Model):
    wallet_name = models.CharField('Название валюты', max_length=200)
    wallet_id = models.CharField('ID', max_length=20)
    wallet_char_code = models.CharField('Char_code', max_length=10)

    class Meta:
        verbose_name = 'Валюта'
        verbose_name_plural = 'Валюты'


class Wallet_value(models.Model):
    wallet = models.ForeignKey(Wallet_indentificator,
                               on_delete=models.CASCADE)
    wallet_nominal = models.IntegerField('Nominal')
    wallet_value = models.FloatField('Value')
    date = models.DateField("Data")

    class Meta:
        verbose_name = 'Курс валюты'
        verbose_name_plural = 'Курс валют'

WebPython/Apps/Wallet/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .load_data import load_data, load_name
from .models import Wallet_indentificator, Wallet_value
from .ClearRepeatedDate import clear_repeated_date


def get_date(request, wallet_name_):
    print('get_date')
    try:
        wallet = Wallet_indentificator.objects.get(wallet_name=wallet_name_)
        wallet_values = Wallet_value.objects.filter(wallet=wallet).order_by(
            '-date')
    except:
        clear_repeated_date()
        wallet = Wallet_indentificator.objects.get(wallet_name=wallet_name_)
        wallet_values = Wallet_value.objects.filter(wallet=wallet).order_by(
            '-date')
    if len(wallet_values) > 10:
        wallet_values = wallet_values[:10]
    dates = []
    for i in wallet_values:
        dates += [str(i.date)]
    return render(request, 'Wallet/choose_date.html',
                  {'wallet': wallet, 'dates_in_memory': dates})


def add_date(request, wallet_name_):
    date_ = '-'.join(request.POST['date'].split('/')[::-1])
    wallet = Wallet_indentificator.objects.get(wallet_name=wallet_name_)
    try:
        load_data(request.POST['date'])
        wallet_info = Wallet_value.objects.get(wallet=wallet, date=date_)
        return render(request, 'Wallet/wallet.html',
                      {'wallet': wallet, 'wallet_info': wallet_info})
    except:
        return HttpResponse('Нет данных на этот день')


def show_wallet(request, wallet_name_, wallet_date_=None):
    if wallet_date_ is None:
        date_ = '-'.join(request.POST['date'].split('/')[::-1])
    else:
        date_ = wallet_date_
    wallet = Wallet_indentificator.objects.get(wallet_name=wallet_name_)
    try:
        wallet_info = Wallet_value.objects.get(wallet=wallet, date=date_)
        return render(request, 'Wallet/wallet.html',
                      {'wallet': wallet, 'wallet_info': wallet_info})
    except:
        return add_date(request, wallet_name_)


def main_page(request):
    wallet_names = []
    wallets_list = Wallet_indentificator.objects.all().order_by('wallet_name')
    if len(wallets_list) == 0:
        load_name()
        wallets_list = Wallet_indentificator.objects.all()
    for wallet in wallets_list:
        wallet_names += [wallet.wallet_name]
    return render(request, 'Wallet/list.html',
                  {'wallets_list': wallet_names})

WebPython/templates/Wallet/choose_date.html
{% extends 'base.html' %}

{% block title %}{{wallet.wallet_name}}{% endblock %}

{% block content %}

<h2 align="center">{{wallet.wallet_name}}({{wallet.wallet_char_code}})</h2>
<hr>
    {% if dates_in_memory %}
        {% for date in dates_in_memory %}
            <a href="{% url 'Wallet:show_wallet' wallet.wallet_name date%}">{{date}}</a><br>
        {% endfor %}
    {% else %}
        Не загружены даты
    {% endif %}
<hr>

    <form action="{% url 'Wallet:show_wallet' wallet.wallet_name%}" method="POST">

        {% csrf_token %}

        <input type="text" required placeholder="дата в формате ДД/ММ/ГГГГ" name="date"><br>

        <button type="submit">Отобразить данную дату</button>
    </form>
{% endblock %}

WebPython/templates/Wallet/list.html
{% extends 'base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
<em>Выберите валюту, чтобы посмотреть информацию о ней </em><br>
<hr>
<p align="center">
    {% if wallets_list %}
        {% for a in wallets_list %}
            <a href="{% url 'Wallet:get_date' a%}">{{a}}</a><br>
        {% endfor %}
    {% else %}
        Статья не найдена
    {% endif %}
</p>

<hr>
<em><font size="1"> (все данные берутся с центробанка. Отсутствие каких либо данных говорит об отсутсвии их на соответствующем сайте)</font></em>
{% endblock %}

WebPython/templates/Wallet/wallet.html
{% extends 'base.html' %}

{% block title %}{{wallet.wallet_name}}{% endblock %}

{% block content %}

<h2 align="center">{{wallet.wallet_name}}({{wallet.wallet_char_code}})</h2>
<hr>
<p align="center">
    Номинал: {{wallet_info.wallet_nominal}} <br>
    Курс: {{wallet_info.wallet_value}} <br>
    <em> Дата: {{wallet_info.date}}</em>
</p>
<hr>
{% endblock %}

WebPython/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Это шаблон{% endblock %}</title>
</head>
<body bgcolor="#F5DEB3">
    {% block content %}{% endblock %}
</body>
</html>